---
service: wingednews-api-v3
frameworkVersion: "3"

package:
  patterns:
    - "!.git/**"
    - "!test/**"
    - "!e2e/**"
    - "!src/**"
    - "!node_modules/**"

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dynamo-stream-plugin
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${env:STAGE, 'development'}
  tableName: "${self:provider.stage}-wingednews"
  stackName: ${self:service}-${self:provider.stage}
  apiName: ${self:service}-${self:provider.stage}
  region: ${env:AWS_REGION, 'eu-central-1'}
  memorySize: 1024
  environment:
    tableName: ${self:provider.tableName}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:BatchGetItem
        - dynamodb:UpdateTimeToLive
      Resource: "arn:aws:dynamodb:eu-north-1:*:*"
functions:
  add_articles:
    handler: src/articles/add_articles.main
    events:
      - schedule: rate(15 minutes)

  smart_get_article:
    handler: src/articles/get_article.main
    events:
      - http:
          path: smart/article/{url}
          method: get
          cors: true
          authorizer: aws_iam

  smart_get_article_feedback:
    handler: src/articles/get_article_feedback.main
    events:
      - http:
          path: smart/feedback/{articleUrl}
          method: get
          cors: true
          authorizer: aws_iam

  add_comment:
    handler: src/articles/add_comment.main
    events:
      - http:
          path: comments
          method: post
          cors: true
          authorizer: aws_iam

  get_article_details:
    handler: src/articles/get_articledetails.main
    events:
      - http:
          path: smart/articledetails/{url}
          method: get
          cors: true
          authorizer: aws_iam

  add_expo_token:
    handler: src/articles/add_expo_token.main
    events:
      - http:
          path: profile/expoToken
          method: post
          cors: true
          authorizer: aws_iam

  add_follower:
    handler: src/articles/add_follower.main
    events:
      - http:
          path: follow
          method: post
          cors: true
          authorizer: aws_iam

  check_follower:
    handler: src/articles/check_follower.main
    events:
      - http:
          path: isfollow
          method: get
          cors: true
          authorizer: aws_iam

  get:
    handler: src/articles/get.main
    events:
      - http:
          path: wingednews/{url}
          method: get
          cors: true
          authorizer: aws_iam

  get_comments:
    handler: src/articles/get_comments.main
    events:
      - http:
          path: comments/{body}
          method: get
          cors: true
          authorizer: aws_iam

  get_followers:
    handler: src/articles/get_followers.main
    events:
      - http:
          path: followers
          method: get
          cors: true
          authorizer: aws_iam

  get_profile:
    handler: src/articles/get_profile.main
    events:
      - http:
          path: profile/{body}
          method: get
          cors: true
          authorizer: aws_iam

  remove_follower:
    handler: src/articles/remove_follower.main
    events:
      - http:
          path: unfollow
          method: post
          cors: true
          authorizer: aws_iam

  set_profile:
    handler: src/articles/set_profile.main
    events:
      - http:
          path: profile/{body}
          method: put
          cors: true
          authorizer: aws_iam

  smart_get_notifications:
    handler: src/articles/get_notifications.main
    events:
      - http:
          path: smart/notifications
          method: get
          cors: true
          authorizer: aws_iam

  get_reported_comments:
    handler: src/articles/get_reported_comments.main
    events:
      - http:
          path: /comments/reported
          method: get
          cors: true
          authorizer: aws_iam

  smart_get_subjects:
    handler: src/articles/get_subjects.main
    events:
      - http:
          path: smart/subjects
          method: get
          cors: true
          authorizer: aws_iam

  get_trending_comments:
    handler: src/articles/get_trending_comments.main
    events:
      - http:
          path: smart/trending/comments
          method: get
          cors: true
          authorizer: aws_iam

  get_trending_interest:
    handler: src/articles/get_trending_interest.main
    events:
      - http:
          path: smart/trending/interest
          method: get
          cors: true
          authorizer: aws_iam

  update_article_feedback:
    handler: src/articles/update_article_feedback.main
    events:
      - http:
          path: smart/article/{url}
          method: put
          cors: true
          authorizer: aws_iam

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
    # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
