Resources:
  newsplitterTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: amount
          AttributeType: N
        - AttributeName: id
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
        - AttributeName: slug
          AttributeType: S
        - AttributeName: addedTS
          AttributeType: N
        - AttributeName: userId
          AttributeType: S
        - AttributeName: postedTs
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      GlobalSecondaryIndexes:
        - IndexName: sortKey-amount-index
          KeySchema:
            - AttributeName: sortKey
              KeyType: HASH
            - AttributeName: amount
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: sortKey-addedTS-index
          KeySchema:
            - AttributeName: sortKey
              KeyType: HASH
            - AttributeName: addedTS
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: slug-index
          KeySchema:
            - AttributeName: slug
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: sortKey-id-stats-index
          KeySchema:
            - AttributeName: sortKey
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: comments-user-timestamp-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: postedTs
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
