Resources:
  WingedNewsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${self:provider.tableName}
      AttributeDefinitions:
        - AttributeName: amount
          AttributeType: N
        - AttributeName: id
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      # Set the capacity to auto-scale
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: sortKey-amount-index
          KeySchema:
            - AttributeName: sortKey
              KeyType: HASH
            - AttributeName: amount
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5