Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E1010
        - E1019
        - E1020

Resources:
  AvatarBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub 'retropop-dispatch-avatars-${self:custom.stage}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - ETag
            MaxAge: 3000

  AppConfigBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub 'retropop-dispatch-config-${self:custom.stage}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  AppConfigSetup:
    Type: Custom::AppConfigSetup
    Properties:
      ServiceToken: !GetAtt InitUnderscoreappUnderscoreconfigLambdaFunction.Arn
      BucketName: !Ref AppConfigBucket
      Stage: ${self:custom.stage}
      ConfigSeedVersion: ${self:custom.appConfigSeedVersion}
